name: flutter_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.6
  another_flushbar: ^1.12.29
  flutter_screenutil: ^5.5.4
  infinite_scroll_pagination: ^3.2.0
  flutter_rating_bar: ^4.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

